apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - gatewayclass.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - certificate.yaml
  - referencegrant.yaml
  - grafana-proxy.yaml
  - grafana-httproute.yaml
