apiVersion: v1
kind: Service
metadata:
  name: homelab-prometheus
  namespace: gateway
  labels:
    app: homelab-prometheus
spec:
  ports:
    - name: http
      port: 4180
      targetPort: 4180
  selector: {}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: homelab-prometheus
  namespace: gateway
  labels:
    kubernetes.io/service-name: homelab-prometheus
addressType: IPv4
endpoints:
  - addresses:
      - 10.0.0.71
ports:
  - name: http
    port: 4180
    protocol: TCP
