apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - cluster-api-operator.yaml
  - cluster-api.yaml
  - chrony.yaml
  - dnsmasq-controller.yaml
  - metallb-operator.yaml
  - metallb.yaml
