apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - namespace.yaml
  - ../../../base/argocd/v3.3.0
  - httproute.yaml
patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-cmd-params-gateway-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
  - path: argocd-rbac-cm-sso-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-dex-server-disable-patch.yaml
    target:
      kind: Deployment
      name: argocd-dex-server
  - path: argocd-repo-server-ksops-patch.yaml
    target:
      kind: Deployment
      name: argocd-repo-server

generators:
  - argocd-secret-sso-generator.yaml
