apiVersion: metal.sidero.dev/v1alpha2
kind: Environment
metadata:
  name: homelab-gpu
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  initrd:
    url: https://pxe.factory.talos.dev/image/21673c24c2599d637798768b9b706349ca91161583257179df72d775af9348c0/v1.12.4/initramfs-amd64.xz
  kernel:
    args:
      - console=tty0
      - console=ttyS0
      - consoleblank=0
      - earlyprintk=ttyS0
      - init_on_alloc=1
      - initrd=initramfs.xz
      - module.sig_enforce=1
      - nvme_core.io_timeout=4294967295
      - printk.devkmsg=on
      - pti=on
      - selinux=1
      - slab_nomerge=
      - talos.platform=metal
    url: https://pxe.factory.talos.dev/image/21673c24c2599d637798768b9b706349ca91161583257179df72d775af9348c0/v1.12.4/kernel-amd64
