apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - environment.yaml
  - serverclasses.yaml
  - cluster.yaml
  - talos-control-plane.yaml
  - metal-cluster.yaml
  - metal-machine-template-cp.yaml
  - talos-config-template.yaml
  - metal-machine-template-worker.yaml
  - machine-deployment.yaml
