apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: homelab-compute-gpu
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterName: homelab
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: homelab-compute-gpu-v1-12-4-2
          namespace: default
      clusterName: homelab
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: homelab-compute-gpu
        namespace: default
      version: v1.35.0
