apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: homelab-workers
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  clusterName: homelab
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: TalosConfigTemplate
          name: homelab-workers-v1-12-3-1
          namespace: default
      clusterName: homelab
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: MetalMachineTemplate
        name: homelab-workers
        namespace: default
      version: v1.35.0
