apiVersion: v1
kind: ConfigMap
metadata:
  name: chrony
data:
  chrony.conf: |
    server 192.168.2.1 iburst

    driftfile /var/lib/chrony/chrony.drift
    makestep 0.1 3

    # Listen on the private cloud gateway address only.
    bindaddress 10.0.0.1

    # Serve NTP only to private cloud clients.
    allow 10.0.0.0/8
