---
apiVersion: v1
kind: Service
metadata:
  name: ntpd
  labels:
    app: chrony
spec:
  ports:
  # port=available to other containers
  - port: 123
    name: ntp
    # targetPort=exposed from inside container
    targetPort: 123
    protocol: UDP
  selector:
    app: chrony
