apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  sso: |
    issuer: https://dex.homelab.ntbc.io
    sessionExpiry: 12h
    clientId:
      name: argo-workflows-sso-oidc
      key: client-id
    clientSecret:
      name: argo-workflows-sso-oidc
      key: client-secret
    redirectUrl: https://argoworkflows.homelab.ntbc.io/oauth2/callback
    scopes:
      - openid
      - profile
      - email
    rbac:
      enabled: true
